### ISSUE TITLE
Cannot call rxjs observerable methods on the observerable from StompService

### ISSUE THREAD

**Issue by martypitt** [ElderByte-/ngx-stomp#8]
As a result of this:
```
import { Observable } from 'rxjs/Observable';
...
readonly connectedClient: Observable<StompClient>;
```

I'm unable to call methods like `.map` or `.flatMap`, as they're missing from that import.

The fix is to change the import -- this should work:

```
import { Observable } from "rxjs/Rx";
```

Here's my usecase -- encapsulate the client subscription, so my services may just directly subscribe on a topic and receive an observable of the messages:
 
```
  subscribe<T>(topic: string): Observable<T> {
    return this.stompService.connectedClient
      .flatMap(client => client.subscribe(topic).messages)
      .map(message => message.bodyJson as T)
  }
```

**Comment by IsNull** [comment]
The operators of rxjs are "addons", so that a library like this does not have to pull in all of them and bloat all clients. This means that you have to pull in operators you require yourself in your project.

Another issue for you is that flatmap has been renamed to mergeMap, and thus the following imports should work for you:

```typescript
import "rxjs/add/operator/mergeMap";
import "rxjs/add/operator/map";
```


Importing `import { Observable } from "rxjs/Rx";` is considered bad practice as it pulls in the whole library.

In fact, rxjs now has switched to a pipe based system to counter the annoying operator imports which can easily be forgotten. See https://github.com/ReactiveX/rxjs/blob/master/doc/pipeable-operators.md

**Comment by martypitt** [comment]
Brilliant, thanks for the detailed response.
